---
- name: Ensure Target Database Exists
  community.postgresql.postgresql_db:
    name: "{{ target_db_name }}"
    login_user: "{{ db_user_admin }}"
    login_password: "{{ db_pass_admin }}"
    login_host: "{{ db_host }}"
    login_port: "{{ global_pg_port }}"
    state: present

- name: Include tasks for creating users and granting privileges
  ansible.builtin.include_tasks:
    file: user_privileges.yml

- name: Check if Target Table Already Exists
  community.postgresql.postgresql_query:
    login_db: "{{ target_db_name }}"
    login_user: "{{ db_user_admin }}"
    login_password: "{{ db_pass_admin }}"
    login_host: "{{ db_host }}"
    login_port: "{{ global_pg_port }}"
    query: "SELECT count(*) FROM pg_tables WHERE schemaname = 'public' AND tablename = '{{ target_table_name }}';"
  register: table_exists_check

- name: Create Target Table if it Does Not Exist
  community.postgresql.postgresql_query:
    login_db: "{{ target_db_name }}"
    login_user: "{{ db_user_admin }}"
    login_password: "{{ db_pass_admin }}"
    login_host: "{{ db_host }}"
    login_port: "{{ global_pg_port }}"
    query: |
      CREATE TABLE {{ target_table_name }} (
        id SERIAL PRIMARY KEY,
        description JSONB NOT NULL DEFAULT '{}'
      );
  when: table_exists_check.query_result[0].count | int == 0

- name: Grant table privileges to gd user
  community.postgresql.postgresql_privs:
    login_host: "{{ db_host }}"
    login_port: "{{ global_pg_port }}"
    login_user: "{{ db_user_admin }}"
    login_password: "{{ db_pass_admin }}"
    login_db: "{{ target_db_name }}"
    schema: public
    objs: "{{ target_table_name }}"
    type: table
    privs: ALL
    role: gd
    state: present