---
- name: Ensure Read/Write and Read-Only Users are Created
  community.postgresql.postgresql_user:
    login_host: "{{ db_host }}"
    login_port: "{{ global_pg_port }}"
    login_user: "{{ db_user_admin }}"
    login_password: "{{ db_pass_admin }}"
    user: "{{ item.name }}"
    password: "{{ item.password }}"
    role_attr_flags: "NOCREATEDB,NOSUPERUSER"
    state: present
  loop:
    - { name: "gd", password: "a@1234" }
    - { name: "gd-view", password: "a@1234view" }

- name: Grant CONNECT Privilege on Database
  community.postgresql.postgresql_privs:
    login_host: "{{ db_host }}"
    login_port: "{{ global_pg_port }}"
    login_user: "{{ db_user_admin }}"
    login_password: "{{ db_pass_admin }}"
    login_db: "{{ target_db_name }}"
    role: "{{ item }}"
    privs: CONNECT
    type: database
    state: present
  loop:
    - gd
    - gd-view

- name: Grant USAGE/CREATE on 'public' Schema
  community.postgresql.postgresql_privs:
    login_host: "{{ db_host }}"
    login_port: "{{ global_pg_port }}"
    login_user: "{{ db_user_admin }}"
    login_password: "{{ db_pass_admin }}"
    login_db: "{{ target_db_name }}"
    role: "{{ item.role }}"
    type: schema
    objs: public
    privs: "{{ item.privs }}"
    state: present
  loop:
    - { role: "gd", privs: "USAGE,CREATE" }
    - { role: "gd-view", privs: "USAGE" }

- name: Grant Privileges on EXISTING Objects
  community.postgresql.postgresql_privs:
    login_host: "{{ db_host }}"
    login_port: "{{ global_pg_port }}"
    login_user: "{{ db_user_admin }}"
    login_password: "{{ db_pass_admin }}"
    login_db: "{{ target_db_name }}"
    objs: ALL_IN_SCHEMA
    schema: public
    type: "{{ item.type }}"
    privs: "{{ item.privs }}"
    role: "{{ item.role }}"
    state: present
  loop:
    - { role: "gd", privs: "ALL", type: "table" }
    - { role: "gd", privs: "ALL", type: "sequence" }
    - { role: "gd-view", privs: "SELECT", type: "table" }

- name: Set DEFAULT Privileges for FUTURE Objects
  community.postgresql.postgresql_privs:
    login_host: "{{ db_host }}"
    login_port: "{{ global_pg_port }}"
    login_user: "{{ db_user_admin }}"
    login_password: "{{ db_pass_admin }}"
    login_db: "{{ target_db_name }}"
    schema: public
    type: default_privs
    objs: "{{ item.objs }}"
    privs: "{{ item.privs }}"
    role: "{{ item.grantee_role }}"
    target_roles: "{{ db_user_admin }}"
    state: present
  loop:
    - { grantee_role: "gd", privs: "ALL", objs: "tables" }
    - { grantee_role: "gd", privs: "ALL", objs: "sequences" }
    - { grantee_role: "gd-view", privs: "SELECT", objs: "tables" }
    - { grantee_role: "gd-view", privs: "SELECT", objs: "sequences" }