---
# Connection Params
db_host: "{{ ansible_default_ipv4.address }}"
db_user_rw: "gd"
db_pass_rw: "a@1234"

# DB Params
target_db_name: "{{ global_pg_dbname }}"
target_table_name: gd_data
base_description_text: 'Automatically inserted row '
