pg_host: "192.168.122.117"
pg_user_ro: "gd-view"
pg_password_ro: "a@1234view"
web_root: "/var/www/html"
script_name: "get_data.php"
target_url: "http://{{ ansible_host }}/{{ script_name }}"
upload_files:
  - get_data.php